backendImage: ghcr.io/hasadna/open-knesset-backend/open-knesset-backend:242d55cddbe170fac6d2f96e2bd9477064fcb787
frontendImage: ghcr.io/hasadna/open-knesset-frontend/open-knesset-frontend:9ac9f9736ae14ee52d503575ccfed794085445f5
