airflowImage: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-airflow:4a0cec775865186f2c1c12c5152dd1992404ff9a
image: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-legacy:4a0cec775865186f2c1c12c5152dd1992404ff9a
