airflowImage: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-airflow:7ee443201d3b4a6b4d3124a84236c84ffcebcfba
image: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-legacy:7ee443201d3b4a6b4d3124a84236c84ffcebcfba
