airflowImage: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-airflow:b84e35ee200f5170e89e8bb43bd3a22e5690d831
image: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-legacy:b84e35ee200f5170e89e8bb43bd3a22e5690d831
